--liquibase formatted sql
--changeset antonio.eduardo:2020-07-23_14_02 endDelimiter:/

CREATE SEQUENCE MV.SEQ_PRODUTOS
	MINVALUE 1
	MAXVALUE 999999999
	START WITH 1
	INCREMENT BY 1
	NOCACHE
/
--rollback DROP SEQUENCE MV.SEQ_PRODUTOS/

CREATE TABLE MV.PRODUTOS (
	id			NUMBER(10) 		NOT NULL,
	descricao	VARCHAR2(200) 	NOT NULL,
	preco		NUMBER			NOT NULL
)/
ALTER TABLE MV.PRODUTOS ADD (
	CONSTRAINT PRODUTOS_PK PRIMARY KEY (id)
)/
--rollback DROP TABLE MV.PRODUTOS/